version: "3.8"
services:
  app:    
    container_name: springboot-mongodb
    image: springboot    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb  
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
      